AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline for ECS Fargate Blue/Green Deployment (triggered by ECR image push)

Parameters:
  ProjectName:
    Type: String
  ECRRepositoryName:
    Type: String
  ClusterName:
    Type: String
  ServiceName:
    Type: String
  TargetGroupBlueName:
    Type: String
  TargetGroupGreenName:
    Type: String
  ALBListenerArn:
    Type: String
  ContainerName:
    Type: String
  ContainerPort:
    Type: Number
  TaskExecutionRoleArn:
    Type: String

Resources:
  # ----------------------------
  # S3 Bucket for Pipeline Artifacts
  # ----------------------------
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-artifacts-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  # ----------------------------
  # IAM Role for CodePipeline
  # ----------------------------
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - iam:PassRole
                  - ecs:*
                  - codedeploy:*
                Resource: "*"

              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeImages
                  - ecr:DescribeRepositories
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ProjectName}-repo

  # ----------------------------
  # CodeDeploy Application
  # ----------------------------
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub "${ProjectName}-codedeploy-app"
      ComputePlatform: ECS

  # ----------------------------
  # CodeDeploy Service Role
  # ----------------------------
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-CodeDeployServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodeDeployECSAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:UpdateService
                  - ecs:DescribeTaskSets
                  - ecs:UpdateServicePrimaryTaskSet
                  - ecs:CreateTaskSet
                  - ecs:DeleteTaskSet
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:ModifyRule
                  - lambda:InvokeFunction
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DeleteAlarms
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${ProjectName}-artifacts-${AWS::AccountId}-${AWS::Region}
                  - !Sub arn:aws:s3:::${ProjectName}-artifacts-${AWS::AccountId}-${AWS::Region}/*
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Ref TaskExecutionRoleArn

  # ----------------------------
  # CodeDeploy Deployment Group
  # ----------------------------
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub "${ProjectName}-dg"
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      ECSServices:
        - ServiceName: !Ref ServiceName
          ClusterName: !Ref ClusterName
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !Ref TargetGroupBlueName
              - Name: !Ref TargetGroupGreenName
            ProdTrafficRoute:
              ListenerArns:
                - !Ref ALBListenerArn

  # ----------------------------
  # CodePipeline Definition (ECR + S3 Sources)
  # ----------------------------
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-pipeline"
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: ECRSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: ECR
                Version: 1
              Configuration:
                RepositoryName: !Ref ECRRepositoryName
                ImageTag: latest
              OutputArtifacts:
                - Name: ECRSourceOutput

            - Name: S3Templates
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Ref ArtifactBucket
                S3ObjectKey: deployment-templates.zip
              OutputArtifacts:
                - Name: TemplatesOutput

        - Name: Deploy
          Actions:
            - Name: ECSBlueGreenDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeployToECS
                Version: 1
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
                TaskDefinitionTemplateArtifact: TemplatesOutput
                TaskDefinitionTemplatePath: taskdef.json
                AppSpecTemplateArtifact: TemplatesOutput
                AppSpecTemplatePath: appspec.yml
              InputArtifacts:
                - Name: TemplatesOutput
                - Name: ECRSourceOutput

  # ----------------------------
  # Role for EventBridge to trigger pipeline
  # ----------------------------
  EventBridgeInvokePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowStartPipeline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${ProjectName}-pipeline

  # ----------------------------
  # EventBridge Rule (Trigger Pipeline on ECR Push)
  # ----------------------------
  ECRPipelineTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source: ["aws.ecr"]
        detail-type: ["ECR Image Action"]
        detail:
          action-type: ["PUSH"]
          result: ["SUCCESS"]
          repository-name: [!Ref ECRRepositoryName]
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${ProjectName}-pipeline
          Id: "ECRPipelineTrigger"
          RoleArn: !GetAtt EventBridgeInvokePipelineRole.Arn

Outputs:
  PipelineName:
    Value: !Ref Pipeline
  CodeDeployApplicationName:
    Value: !Ref CodeDeployApplication
  CodeDeployDeploymentGroupName:
    Value: !Ref CodeDeployDeploymentGroup
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
